import FWCore.ParameterSet.Config as cms

process = cms.Process('GenLevel')


process.TFileService = cms.Service("TFileService",
                                   fileName = cms.string("GenLevelAnalysis.root"),
                                   closeFileFast = cms.untracked.bool(True)
                                   )

process.muonParticlesInAcc = cms.EDFilter("GenParticleSelector",
                                     filter = cms.bool(False),
                                     src = cms.InputTag("genParticles"),
                                     cut = cms.string('pt > 1. && abs(pdgId) == 13 && abs(eta) < 2.4'),
                                     stableOnly = cms.bool(True)
 )


process.threeMuonFilter = cms.EDFilter("CandViewCountFilter",
                                       src = cms.InputTag("muonParticlesInAcc"),
                                       minNumber = cms.uint32(3))



process.load("TrackingTools.TransientTrack.TransientTrackBuilder_cfi")
process.load("Configuration.StandardSequences.Geometry_cff")
process.load("Configuration.StandardSequences.FrontierConditions_GlobalTag_cff")
process.load("Configuration.StandardSequences.MagneticField_cff")
process.GlobalTag.globaltag = 'START44_V7::All'

# Source
process.source = cms.Source("PoolSource",
                            fileNames = cms.untracked.vstring(
                                'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_000.root',
                                'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_002.root',
                                'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_003.root',
                                'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_004.root',
                                'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_005.root',
                                'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_006.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_007.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_008.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_009.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_010.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_011.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_012.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_013.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_014.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_015.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_016.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_017.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_018.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_019.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_020.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_021.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_022.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_023.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_024.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_025.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_026.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_027.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_028.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_029.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_030.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_031.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_032.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_033.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_034.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_035.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_036.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_037.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_038.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_039.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_040.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_041.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_042.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_043.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_044.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_045.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_046.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_047.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_048.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_049.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_050.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_051.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_052.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_053.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_054.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_055.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_056.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_057.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_058.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_059.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_060.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_061.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_062.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_063.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_064.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_065.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_066.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_067.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_068.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_069.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_070.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_071.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_072.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_073.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_074.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_075.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_076.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_077.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_078.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_079.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_080.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_081.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_082.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_083.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_084.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_085.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_086.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_087.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_088.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_089.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_090.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_091.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_092.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_093.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_094.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_095.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_096.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_097.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_098.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_099.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_100.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_101.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_102.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_103.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_104.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_105.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_106.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_107.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_108.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_109.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_110.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_111.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_112.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_113.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_115.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_116.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_117.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_118.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_119.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_120.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_121.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_122.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_123.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_124.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_125.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_126.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_127.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_128.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_129.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_130.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_131.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_132.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_133.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_134.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_135.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_136.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_137.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_138.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_139.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_140.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_141.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_142.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_143.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_144.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_145.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_146.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_147.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_148.root',
'file:/data1/Tau3Mu/FastSim/DsTau3Mu_GEN_FASTSIM_HLT_PU_2_AOD/DsTau3Mu_149.root',)
                            )
process.maxEvents = cms.untracked.PSet(input = cms.untracked.int32(-1))



process.genLevelAnalysis = cms.EDAnalyzer('GenLevelAnalysis')

process.analysisPath = cms.Path(process.muonParticlesInAcc + process.threeMuonFilter + process.genLevelAnalysis)
